services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: supplysight
      POSTGRES_PASSWORD: supplysight
      POSTGRES_DB: supplysight
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
